CREATE EXTENSION IF NOT EXISTS pgtap;
SET search_path TO public, extensions;

BEGIN;

SELECT plan(70);

SELECT is(
  (
    SELECT pg_catalog.jsonb_build_object('name', name, 'public', public)
    FROM storage.buckets
    WHERE id = 'billing-evidence'
  ),
  '{"name":"billing-evidence","public":false}'::jsonb,
  'billing evidence uses one private bucket'
);

SELECT is(
  (
    SELECT count(*)
    FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND roles @> ARRAY['authenticated']::name[]
      AND (
        coalesce(qual, '') ILIKE '%billing-evidence%'
        OR coalesce(with_check, '') ILIKE '%billing-evidence%'
      )
  ),
  0::bigint,
  'no authenticated Storage object policy names the billing evidence bucket'
);

SELECT is(
  (
    SELECT count(*)
    FROM pg_class
    WHERE oid = ANY (ARRAY[
      'public.billing_evidence_objects'::regclass,
      'public.billing_evidence_access_events'::regclass
    ])
      AND relrowsecurity
  ),
  2::bigint,
  'both evidence relations enable row-level security'
);

SELECT is(
  (
    SELECT count(*)
    FROM pg_class
    WHERE oid = ANY (ARRAY[
      'public.billing_evidence_objects'::regclass,
      'public.billing_evidence_access_events'::regclass
    ])
      AND relforcerowsecurity
  ),
  2::bigint,
  'both evidence relations force row-level security'
);

SELECT is(
  (
    SELECT array_agg(column_name::text ORDER BY ordinal_position)
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'billing_evidence_support_safe'
  ),
  ARRAY[
    'id', 'organization_id', 'account_id', 'mime_type', 'size_bytes',
    'inspection_status', 'inspection_reason_code', 'retention_expires_at',
    'is_held', 'lifecycle_status', 'end_reason', 'created_at', 'updated_at',
    'kind', 'original_filename', 'uploader_label'
  ]::text[],
  'support view exposes only the explicit safe column inventory'
);

SELECT is(
  (
    SELECT count(*)
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'billing_evidence_support_safe'
      AND column_name ~ '(path|sha|signed|token|contact|email|phone|provider|payload)'
  ),
  0::bigint,
  'support view omits paths, signed data, contacts, and provider payload fields'
);

SELECT ok(
  (
    SELECT reloptions @> ARRAY['security_invoker=true']
    FROM pg_class
    WHERE oid = 'public.billing_evidence_support_safe'::regclass
  ),
  'support view executes with invoker security'
);

SELECT is(
  (
    SELECT is_generated
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'billing_evidence_objects'
      AND column_name = 'object_path'
  ),
  'ALWAYS',
  'evidence paths are generated by PostgreSQL rather than accepted from callers'
);

SELECT is(
  (
    SELECT object_path
    FROM public.billing_evidence_objects
    WHERE id = '21000000-0000-0000-0000-000000000601'
  ),
  '21000000-0000-0000-0000-000000000100/21000000-0000-0000-0000-000000000200/21000000-0000-0000-0000-000000000601',
  'generated paths contain only server-owned opaque identifiers'
);

SELECT ok(
  (
    SELECT coalesce(array_to_string(proconfig, ','), '') IN ('search_path=', 'search_path=""')
    FROM pg_proc
    WHERE oid = 'private.billing_evidence_protect_state()'::regprocedure
  ),
  'evidence state trigger has an empty search_path'
);
SELECT ok(
  (
    SELECT coalesce(array_to_string(proconfig, ','), '') IN ('search_path=', 'search_path=""')
    FROM pg_proc
    WHERE oid = 'private.billing_evidence_event_immutable()'::regprocedure
  ),
  'evidence event trigger has an empty search_path'
);
SELECT ok(
  (
    SELECT coalesce(array_to_string(proconfig, ','), '') IN ('search_path=', 'search_path=""')
    FROM pg_proc
    WHERE oid = 'private.billing_actor_has_capability(uuid,uuid,uuid,text)'::regprocedure
  ),
  'service-side actor capability helper has an empty search_path'
);
SELECT ok(
  (
    SELECT coalesce(array_to_string(proconfig, ','), '') IN ('search_path=', 'search_path=""')
    FROM pg_proc
    WHERE oid = 'private.billing_begin_evidence_upload(uuid,uuid,text,bigint,text)'::regprocedure
  ),
  'private upload helper has an empty search_path'
);
SELECT ok(
  (
    SELECT coalesce(array_to_string(proconfig, ','), '') IN ('search_path=', 'search_path=""')
    FROM pg_proc
    WHERE oid = 'public.begin_billing_evidence_upload(uuid,uuid,text,bigint,text)'::regprocedure
  ),
  'service-only upload entry point has an empty search_path'
);
SELECT ok(
  (
    SELECT coalesce(array_to_string(proconfig, ','), '') IN ('search_path=', 'search_path=""')
    FROM pg_proc
    WHERE oid = 'private.billing_finalize_evidence_inspection(uuid,uuid,text,text,text,text,text)'::regprocedure
  ),
  'private inspection helper has an empty search_path'
);
SELECT ok(
  (
    SELECT coalesce(array_to_string(proconfig, ','), '') IN ('search_path=', 'search_path=""')
    FROM pg_proc
    WHERE oid = 'public.finalize_billing_evidence_inspection(uuid,uuid,text,text,text,text,text)'::regprocedure
  ),
  'public inspection entry point has an empty search_path'
);
SELECT ok(
  (
    SELECT coalesce(array_to_string(proconfig, ','), '') IN ('search_path=', 'search_path=""')
    FROM pg_proc
    WHERE oid = 'private.billing_authorize_evidence_access(uuid,text)'::regprocedure
  ),
  'private access helper has an empty search_path'
);
SELECT ok(
  (
    SELECT coalesce(array_to_string(proconfig, ','), '') IN ('search_path=', 'search_path=""')
    FROM pg_proc
    WHERE oid = 'public.authorize_billing_evidence_access(uuid,text)'::regprocedure
  ),
  'public access entry point has an empty search_path'
);

SELECT ok(
  has_function_privilege(
    'service_role',
    'public.begin_billing_evidence_upload(uuid,uuid,text,bigint,text,text,text)',
    'EXECUTE'
  )
  AND NOT has_function_privilege(
    'service_role',
    'public.begin_billing_evidence_upload(uuid,uuid,text,bigint,text)',
    'EXECUTE'
  )
  AND NOT has_function_privilege(
    'authenticated',
    'public.begin_billing_evidence_upload(uuid,uuid,text,bigint,text,text,text)',
    'EXECUTE'
  )
  AND NOT has_function_privilege(
    'anon',
    'public.begin_billing_evidence_upload(uuid,uuid,text,bigint,text,text,text)',
    'EXECUTE'
  ),
  'only service execution can create complete caller-bound upload metadata'
);
SELECT ok(
  NOT has_function_privilege(
    'public',
    'private.billing_finalize_evidence_inspection(uuid,uuid,text,text,text,text,text)',
    'EXECUTE'
  )
  AND NOT has_function_privilege(
    'authenticated',
    'private.billing_finalize_evidence_inspection(uuid,uuid,text,text,text,text,text)',
    'EXECUTE'
  ),
  'inspection helper cannot be called directly'
);
SELECT ok(
  NOT has_function_privilege(
    'public',
    'private.billing_authorize_evidence_access(uuid,text)',
    'EXECUTE'
  )
  AND NOT has_function_privilege(
    'authenticated',
    'private.billing_authorize_evidence_access(uuid,text)',
    'EXECUTE'
  ),
  'access helper cannot be called directly'
);
SELECT ok(
  has_function_privilege(
    'authenticated',
    'public.finalize_billing_evidence_inspection(uuid,uuid,text,text,text,text,text)',
    'EXECUTE'
  )
  AND has_function_privilege(
    'authenticated',
    'public.authorize_billing_evidence_access(uuid,text)',
    'EXECUTE'
  ),
  'authenticated callers receive only the two caller-bound entry points'
);
SELECT ok(
  NOT has_function_privilege(
    'anon',
    'public.finalize_billing_evidence_inspection(uuid,uuid,text,text,text,text,text)',
    'EXECUTE'
  )
  AND NOT has_function_privilege(
    'anon',
    'public.authorize_billing_evidence_access(uuid,text)',
    'EXECUTE'
  ),
  'anonymous callers receive no evidence command entry point'
);

SELECT ok(
  NOT has_table_privilege('authenticated', 'public.billing_evidence_objects', 'SELECT')
  AND has_column_privilege('authenticated', 'public.billing_evidence_objects', 'id', 'SELECT')
  AND has_column_privilege('authenticated', 'public.billing_evidence_objects', 'inspection_status', 'SELECT')
  AND has_column_privilege('authenticated', 'public.billing_evidence_objects', 'retention_expires_at', 'SELECT')
  AND NOT has_column_privilege('authenticated', 'public.billing_evidence_objects', 'object_path', 'SELECT')
  AND NOT has_column_privilege('authenticated', 'public.billing_evidence_objects', 'sha256', 'SELECT')
  AND NOT has_table_privilege('authenticated', 'public.billing_evidence_objects', 'INSERT')
  AND NOT has_table_privilege('authenticated', 'public.billing_evidence_objects', 'UPDATE')
  AND NOT has_table_privilege('authenticated', 'public.billing_evidence_objects', 'DELETE'),
  'authenticated callers receive only safe evidence metadata columns and cannot mutate them'
);
SELECT ok(
  has_table_privilege('authenticated', 'public.billing_evidence_access_events', 'SELECT')
  AND NOT has_table_privilege('authenticated', 'public.billing_evidence_access_events', 'INSERT')
  AND NOT has_table_privilege('authenticated', 'public.billing_evidence_access_events', 'UPDATE')
  AND NOT has_table_privilege('authenticated', 'public.billing_evidence_access_events', 'DELETE'),
  'authenticated callers cannot append or rewrite access history directly'
);
SELECT ok(
  has_table_privilege('authenticated', 'public.billing_evidence_support_safe', 'SELECT'),
  'authenticated callers can query the safe support view through underlying RLS'
);

-- Human reviewer: scoped visibility, no direct mutation, and exact state denials.
SELECT set_config('request.jwt.claim.sub', '21000000-0000-0000-0000-000000000003', true);
SELECT set_config('request.jwt.claims', '{"sub":"21000000-0000-0000-0000-000000000003","role":"authenticated"}', true);
SET LOCAL ROLE authenticated;

SELECT is(
  (SELECT count(*) FROM public.billing_evidence_objects),
  7::bigint,
  'reviewer sees only evidence in the assigned account'
);
SELECT is(
  (SELECT count(*) FROM public.billing_evidence_support_safe),
  7::bigint,
  'support view preserves the reviewer account boundary'
);
SELECT throws_ok(
  $$INSERT INTO storage.objects (bucket_id, name)
    VALUES ('billing-evidence', 'caller-controlled/path')$$,
  '42501',
  'new row violates row-level security policy for table "objects"',
  'authenticated callers cannot create direct billing evidence Storage objects'
);
SELECT throws_ok(
  $$UPDATE public.billing_evidence_objects
    SET lifecycle_status = 'disabled', ended_at = now(), end_reason = 'forbidden'
    WHERE id = '21000000-0000-0000-0000-000000000601'$$,
  '42501',
  'permission denied for table billing_evidence_objects',
  'authenticated callers cannot mutate evidence metadata directly'
);
SELECT is(
  public.finalize_billing_evidence_inspection(
    '21000000-0000-0000-0000-000000000606',
    '21000000-0000-0000-0000-000000000502',
    'scanner-alpha-fixture', 'scanner-fixture-v1',
    'clean', 'SCAN_CLEAN', 'human-inspection-denied-0001'
  )->>'reason_code',
  'INSPECTION_NOT_AUTHORIZED',
  'human reviewer cannot impersonate the inspection automation principal'
);
SELECT is(
  public.authorize_billing_evidence_access(
    '21000000-0000-0000-0000-000000000606', 'review'
  )->>'reason_code',
  'EVIDENCE_QUARANTINED',
  'quarantined evidence is denied'
);
SELECT is(
  public.authorize_billing_evidence_access(
    '21000000-0000-0000-0000-000000000602', 'review'
  )->>'reason_code',
  'EVIDENCE_REJECTED',
  'rejected evidence is denied'
);
SELECT is(
  public.authorize_billing_evidence_access(
    '21000000-0000-0000-0000-000000000603', 'review'
  )->>'reason_code',
  'EVIDENCE_EXPIRED',
  'retention-expired evidence is denied'
);
SELECT is(
  public.authorize_billing_evidence_access(
    '21000000-0000-0000-0000-000000000604', 'review'
  )->>'reason_code',
  'EVIDENCE_HELD',
  'held evidence is denied'
);
SELECT is(
  public.authorize_billing_evidence_access(
    '21000000-0000-0000-0000-000000000605', 'review'
  )->>'reason_code',
  'EVIDENCE_NOT_ACTIVE',
  'disabled evidence is denied'
);
SELECT is(
  public.authorize_billing_evidence_access(
    '21000000-0000-0000-0000-000000000601', 'raw-path'
  )->>'reason_code',
  'PURPOSE_NOT_ALLOWED',
  'an unknown purpose is normalized and denied'
);
SELECT is(
  public.authorize_billing_evidence_access(
    '22000000-0000-0000-0000-000000000600', 'review'
  )->>'reason_code',
  'ACCESS_NOT_AUTHORIZED',
  'cross-organization evidence access is denied without revealing state'
);
SELECT ok(
  (
    SELECT result->>'reason_code' = 'ACCESS_ALLOWED'
      AND (result->>'capability_eligible')::boolean
      AND result ? 'expires_at'
      AND NOT result ? 'object_path'
      AND NOT result ? 'signed_url'
    FROM (
      SELECT public.authorize_billing_evidence_access(
        '21000000-0000-0000-0000-000000000601', 'review'
      ) AS result
    ) AS decision
  ),
  'reviewer receives only a short-lived capability-eligible decision for clean evidence'
);

RESET ROLE;

SELECT is(
  (SELECT inspection_status FROM public.billing_evidence_objects WHERE id = '21000000-0000-0000-0000-000000000606'),
  'quarantined',
  'human inspection attempt leaves evidence state unchanged'
);

-- Automation: exact scanner grant is mandatory and inspection is atomic.
SELECT set_config('request.jwt.claim.sub', '21000000-0000-0000-0000-000000000006', true);
SELECT set_config('request.jwt.claims', '{"sub":"21000000-0000-0000-0000-000000000006","role":"authenticated"}', true);
SET LOCAL ROLE authenticated;

SELECT is(
  public.finalize_billing_evidence_inspection(
    '21000000-0000-0000-0000-000000000606',
    '21000000-0000-0000-0000-000000000502',
    'scanner-wrong-fixture', 'scanner-fixture-v1',
    'clean', 'SCAN_CLEAN', 'wrong-scanner-denied-0001'
  )->>'result',
  'denied',
  'inspection rejects a mismatched scanner provider reference'
);
SELECT is(
  public.finalize_billing_evidence_inspection(
    '22000000-0000-0000-0000-000000000606',
    '21000000-0000-0000-0000-000000000502',
    'scanner-alpha-fixture', 'scanner-fixture-v1',
    'clean', 'SCAN_CLEAN', 'cross-inspection-denied-0001'
  )->>'result',
  'denied',
  'inspection cannot use an Alpha grant for Bravo evidence'
);
SELECT ok(
  (
    SELECT result->>'result' = 'applied'
      AND result->>'decision' = 'clean'
      AND NOT result ? 'object_path'
    FROM (
      SELECT public.finalize_billing_evidence_inspection(
        '21000000-0000-0000-0000-000000000600',
        '21000000-0000-0000-0000-000000000502',
        'scanner-alpha-fixture', 'scanner-fixture-v1',
        'clean', 'SCAN_CLEAN', 'inspection-applied-0001'
      ) AS result
    ) AS decision
  ),
  'exact automation grant records one clean decision without exposing the path'
);
SELECT is(
  public.finalize_billing_evidence_inspection(
    '21000000-0000-0000-0000-000000000600',
    '21000000-0000-0000-0000-000000000502',
    'scanner-alpha-fixture', 'scanner-fixture-v1',
    'clean', 'SCAN_CLEAN', 'inspection-applied-0001'
  )->>'result',
  'duplicate',
  'inspection replay returns the prior command outcome without a second transition'
);

RESET ROLE;

SELECT is(
  (
    SELECT pg_catalog.jsonb_build_object(
      'status', inspection_status,
      'principal', inspection_principal_id,
      'grant', inspection_grant_id,
      'reason', inspection_reason_code
    )
    FROM public.billing_evidence_objects
    WHERE id = '21000000-0000-0000-0000-000000000600'
  ),
  '{"status":"clean","principal":"21000000-0000-0000-0000-000000000400","grant":"21000000-0000-0000-0000-000000000502","reason":"SCAN_CLEAN"}'::jsonb,
  'inspection state binds the exact principal, grant, decision, and reason'
);
SELECT is(
  (
    SELECT count(*)
    FROM public.billing_automation_executions
    WHERE command_name = 'evidence.inspect'
  ),
  1::bigint,
  'only the authorized inspection creates an automation execution receipt'
);
SELECT is(
  (
    SELECT actions_consumed
    FROM public.billing_automation_grants
    WHERE id = '21000000-0000-0000-0000-000000000502'
  ),
  1,
  'denied inspections consume no scanner action allowance'
);
SELECT is(
  (
    SELECT count(*)
    FROM public.billing_audit_events
    WHERE action = 'evidence.inspection'
      AND subject_id = '21000000-0000-0000-0000-000000000600'
      AND result = 'succeeded'
      AND details = '{"decision":"clean"}'::jsonb
  ),
  1::bigint,
  'authorized inspection appends one allowlisted audit event'
);

-- Additional human purpose combinations.
SELECT set_config('request.jwt.claim.sub', '21000000-0000-0000-0000-000000000002', true);
SELECT set_config('request.jwt.claims', '{"sub":"21000000-0000-0000-0000-000000000002","role":"authenticated"}', true);
SET LOCAL ROLE authenticated;
SELECT is(
  public.authorize_billing_evidence_access(
    '21000000-0000-0000-0000-000000000601', 'download'
  )->>'reason_code',
  'ACCESS_ALLOWED',
  'operator can request clean evidence for download'
);
RESET ROLE;

SELECT set_config('request.jwt.claim.sub', '21000000-0000-0000-0000-000000000005', true);
SELECT set_config('request.jwt.claims', '{"sub":"21000000-0000-0000-0000-000000000005","role":"authenticated"}', true);
SET LOCAL ROLE authenticated;
SELECT is(
  public.authorize_billing_evidence_access(
    '21000000-0000-0000-0000-000000000601', 'download'
  )->>'reason_code',
  'ACCESS_ALLOWED',
  'bound customer can request clean evidence for download'
);
RESET ROLE;

SELECT set_config('request.jwt.claim.sub', '21000000-0000-0000-0000-000000000004', true);
SELECT set_config('request.jwt.claims', '{"sub":"21000000-0000-0000-0000-000000000004","role":"authenticated"}', true);
SET LOCAL ROLE authenticated;
SELECT is(
  public.authorize_billing_evidence_access(
    '21000000-0000-0000-0000-000000000601', 'audit'
  )->>'reason_code',
  'ACCESS_ALLOWED',
  'auditor can request clean evidence for the audit purpose'
);
SELECT is(
  public.authorize_billing_evidence_access(
    '21000000-0000-0000-0000-000000000601', 'download'
  )->>'reason_code',
  'ACCESS_NOT_AUTHORIZED',
  'auditor cannot widen audit authority into download authority'
);
RESET ROLE;

SELECT is(
  (SELECT count(*) FROM public.billing_evidence_access_events),
  12::bigint,
  'every found-object access attempt appends exactly one access event'
);
SELECT is(
  (SELECT count(*) FROM public.billing_evidence_access_events WHERE result = 'allowed'),
  4::bigint,
  'only the four authorized role and purpose combinations are allowed'
);
SELECT is(
  (
    SELECT pg_catalog.jsonb_object_agg(reason_code, event_count ORDER BY reason_code)
    FROM (
      SELECT reason_code, count(*) AS event_count
      FROM public.billing_evidence_access_events
      WHERE result = 'denied'
      GROUP BY reason_code
    ) AS reasons
  ),
  '{"ACCESS_NOT_AUTHORIZED":2,"EVIDENCE_EXPIRED":1,"EVIDENCE_HELD":1,"EVIDENCE_NOT_ACTIVE":1,"EVIDENCE_QUARANTINED":1,"EVIDENCE_REJECTED":1,"PURPOSE_NOT_ALLOWED":1}'::jsonb,
  'denied access history records the exact safe reason inventory'
);
SELECT is(
  (
    SELECT count(*)
    FROM public.billing_evidence_access_events
    WHERE actor_type = 'customer'
      AND actor_id = '21000000-0000-0000-0000-000000000005'
      AND result = 'allowed'
  ),
  1::bigint,
  'customer access history preserves the caller type and identity'
);
SELECT ok(
  NOT EXISTS (
    SELECT 1
    FROM public.billing_evidence_access_events
    WHERE result = 'allowed'
      AND (
        capability_expires_at IS NULL
        OR capability_expires_at <= created_at
        OR capability_expires_at > created_at + interval '60 seconds'
      )
  ),
  'every allowed decision has a bounded capability expiry'
);
SELECT is(
  (
    SELECT count(*)
    FROM public.billing_audit_events
    WHERE action = 'evidence.access'
  ),
  12::bigint,
  'every access decision appends one matching billing audit event'
);
SELECT ok(
  NOT EXISTS (
    SELECT 1
    FROM public.billing_audit_events
    WHERE action = 'evidence.access'
      AND (
        details ? 'object_path'
        OR details ? 'sha256'
        OR details ? 'signed_url'
        OR details ? 'provider_reference'
      )
  ),
  'evidence access audits contain no path, byte hash, signed data, or provider reference'
);

-- Owner-level invariant checks prove history and state cannot be rewritten even by direct SQL.
SELECT throws_ok(
  $$UPDATE public.billing_evidence_objects
    SET account_id = '22000000-0000-0000-0000-000000000200'
    WHERE id = '21000000-0000-0000-0000-000000000601'$$,
  'P0001',
  'Evidence scope and byte metadata are immutable',
  'evidence account scope cannot be changed'
);
SELECT throws_ok(
  $$UPDATE public.billing_evidence_objects
    SET sha256 = repeat('f', 64)
    WHERE id = '21000000-0000-0000-0000-000000000601'$$,
  'P0001',
  'Evidence scope and byte metadata are immutable',
  'evidence byte identity cannot be changed'
);
SELECT throws_ok(
  $$UPDATE public.billing_evidence_objects
    SET inspection_status = 'rejected', inspection_reason_code = 'SCAN_REJECTED'
    WHERE id = '21000000-0000-0000-0000-000000000601'$$,
  'P0001',
  'Evidence inspection decision is immutable',
  'a final inspection decision cannot be rewritten'
);
SELECT throws_ok(
  $$UPDATE public.billing_evidence_objects
    SET lifecycle_status = 'active', ended_at = NULL, end_reason = NULL
    WHERE id = '21000000-0000-0000-0000-000000000605'$$,
  'P0001',
  'Evidence lifecycle cannot be reopened',
  'disabled evidence cannot be reopened'
);
SELECT lives_ok(
  $$UPDATE public.billing_evidence_objects
    SET hold_released_at = now(), hold_release_reason = 'fixture hold released'
    WHERE id = '21000000-0000-0000-0000-000000000604'$$,
  'an active hold can be ended with an explicit reason'
);
SELECT ok(
  (
    SELECT hold_released_at IS NOT NULL
      AND hold_release_reason = 'fixture hold released'
    FROM public.billing_evidence_objects
    WHERE id = '21000000-0000-0000-0000-000000000604'
  ),
  'hold release history remains explicit'
);
SELECT throws_ok(
  $$UPDATE public.billing_evidence_objects
    SET hold_reason = 'rewritten hold'
    WHERE id = '21000000-0000-0000-0000-000000000604'$$,
  'P0001',
  'Evidence hold history is immutable',
  'ended hold history cannot be rewritten'
);
SELECT throws_ok(
  $$UPDATE public.billing_evidence_access_events
    SET reason_code = reason_code
    WHERE id = (SELECT min(id) FROM public.billing_evidence_access_events)$$,
  'P0001',
  'Evidence access events are append-only',
  'access events cannot be updated'
);
SELECT throws_ok(
  $$DELETE FROM public.billing_evidence_access_events
    WHERE id = (SELECT min(id) FROM public.billing_evidence_access_events)$$,
  'P0001',
  'Evidence access events are append-only',
  'access events cannot be deleted'
);
SELECT throws_ok(
  $$UPDATE public.billing_audit_events
    SET reason = reason
    WHERE action = 'evidence.access'$$,
  'P0001',
  'Billing audit events are append-only',
  'evidence audit history cannot be updated'
);
SELECT throws_ok(
  $$DELETE FROM public.billing_audit_events
    WHERE action = 'evidence.access'$$,
  'P0001',
  'Billing audit events are append-only',
  'evidence audit history cannot be deleted'
);

SELECT * FROM finish();
ROLLBACK;
